<?php
/**
 * Monolit Shield (Hardened) — MU Plugin
 * URL: https://monolit.digital
 * Description: Zero-config WordPress hardening for developers (MU-plugin). Admin aliasing, user-enum protection, HTML/JSON-LD sanitation, secure headers.
 * Version: 1.0.0
 * Author: Monolit Digital
 * Text Domain: monolit-shield
 */
if ( ! defined( 'ABSPATH' ) ) exit;
// Admin alias (wp-config.php). Default: admin-portal.
if ( ! defined( 'MSHIELD_ADMIN_SLUG' ) ) define( 'MSHIELD_ADMIN_SLUG', 'admin-portal' );
if ( defined( 'MSHIELD_LOADED' ) ) return;
define( 'MSHIELD_LOADED', true );
if ( ! class_exists( 'Monolit_Shield' ) ) :
final class Monolit_Shield {
	public static function boot() : void { static $i=null; $i ?: $i = new self; }
	private function __construct() {
		add_action( 'init',                  [ $this, 'on_init' ] );
		add_action( 'template_redirect',     [ $this, 'start_output_sanitizer' ], 1 );
		add_action( 'send_headers',          [ $this, 'send_security_headers' ] );
		add_action( 'wp_enqueue_scripts',    [ $this, 'on_enqueue_front' ], 20 );
		add_action( 'admin_enqueue_scripts', [ $this, 'on_enqueue_admin' ], 20 );
		// Rewrite admin URLs generated by WP to the alias.
		add_filter( 'admin_url',         [ $this, 'mask_admin_url' ], 10, 3 );
		add_filter( 'network_admin_url', [ $this, 'mask_admin_url' ], 10, 3 );
		add_filter( 'user_admin_url',    [ $this, 'mask_admin_url' ], 10, 3 );
		add_filter( 'site_url',          [ $this, 'mask_site_admin_url' ], 10, 4 );
		$this->ensure_blank_comments_view();
	}
	public function on_init() : void {
		add_filter( 'xmlrpc_enabled', '__return_false' );
		add_filter( 'pre_option_enable_xmlrpc', '__return_zero' );
		add_filter( 'pre_update_option_enable_xmlrpc', '__return_zero' );
		add_filter( 'pre_option_default_pingback_flag', '__return_zero' );
		add_filter( 'wp_headers', [ $this, 'remove_x_pingback_header' ], 11 );
		remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
		remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
		remove_action( 'wp_print_styles', 'print_emoji_styles' );
		remove_action( 'admin_print_styles', 'print_emoji_styles' );
		remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
		remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
		remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
		add_filter( 'tiny_mce_plugins', [ $this, 'disable_emojis_tinymce' ] );
		add_filter( 'emoji_svg_url', '__return_false' );
		remove_action( 'wp_head', 'wp_oembed_add_host_js' );
		remove_action( 'wp_head', 'wp_oembed_add_discovery_links' );
		add_filter( 'embed_oembed_discover', '__return_false' );
		add_filter( 'rewrite_rules_array', [ $this, 'disable_embeds_rewrites' ] );
		add_action( 'do_feed',       [ $this, 'disable_rss' ], 1 );
		add_action( 'do_feed_rdf',   [ $this, 'disable_rss' ], 1 );
		add_action( 'do_feed_rss',   [ $this, 'disable_rss' ], 1 );
		add_action( 'do_feed_rss2',  [ $this, 'disable_rss' ], 1 );
		add_action( 'do_feed_atom',  [ $this, 'disable_rss' ], 1 );
		add_filter( 'feed_links_show_comments_feed', '__return_false' );
		add_filter( 'the_generator', '__return_empty_string' );
		add_action( 'pre_ping', [ $this, 'disable_self_pingbacks' ] );
		$this->disable_comments_everywhere();
		add_action( 'wp_enqueue_scripts', function () {
			if ( ! is_user_logged_in() ) wp_deregister_style( 'dashicons' );
		}, 100 );
		if ( ! ( defined('SCRIPT_DEBUG') && SCRIPT_DEBUG ) ) {
			add_filter( 'wp_default_scripts', [ $this, 'remove_jquery_migrate' ] );
		}
		remove_action( 'wp_head', 'rsd_link' );
		remove_action( 'wp_head', 'wlwmanifest_link' );
		remove_action( 'wp_head', 'wp_generator' );
		remove_action( 'wp_head', 'rest_output_link_wp_head', 10 );
		remove_action( 'template_redirect', 'rest_output_link_header', 11 );
		remove_action( 'wp_head', 'wp_shortlink_wp_head', 10, 0 );
        add_filter( 'rest_authentication_errors', [ $this, 'rest_harden' ] );
		add_action( 'template_redirect', [ $this, 'block_author_enum' ], 0 );
		add_filter( 'author_rewrite_rules', '__return_empty_array' );
		add_filter( 'wp_sitemaps_add_provider', function( $provider, $name ){
			return ( 'users' === $name ) ? false : $provider;
		}, 10, 2 );
		add_filter( 'sanitize_file_name', [ $this, 'sanitize_filename_latin' ], 10, 1 );
		add_filter( 'the_content', [ $this, 'cloak_emails' ], 12 );
		add_filter( 'widget_text', [ $this, 'cloak_emails' ], 12 );
		add_filter( 'nav_menu_description', [ $this, 'cloak_emails' ], 12 );
		add_filter( 'style_loader_src',  [ $this, 'strip_asset_ver_front' ], 10, 2 );
		add_filter( 'script_loader_src', [ $this, 'strip_asset_ver_front' ], 10, 2 );
		if ( ! defined( 'ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS' ) ) {
			define( 'ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS', true );
		}
		add_action( 'wp', function () {
			if ( did_action( 'elementor/loaded' ) && class_exists( '\Elementor\Plugin' ) ) {
				$front = \Elementor\Plugin::$instance->frontend ?? null;
				if ( $front && method_exists( $front, 'print_meta_generator' ) ) {
					remove_action( 'wp_head', [ $front, 'print_meta_generator' ] );
				}
			}
		}, 1 );
		add_filter( 'login_redirect', function( $redirect_to, $requested, $user ) {
			return admin_url();
		}, 10, 3 );
	}
	public function on_enqueue_front() : void { $this->dequeue_google_fonts(); }
	public function on_enqueue_admin() : void {}
	public function start_output_sanitizer() : void {
		if ( is_admin() || wp_doing_ajax() || is_feed() ) return;
		$script = basename( $_SERVER['PHP_SELF'] ?? '' );
		if ( $script === 'wp-login.php' ) return;
		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) return;
		$uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';
		if ( strpos( $uri, '/wp-json/' ) === 0 ) return;
		if ( isset( $_GET['preview'] ) ) return;
		$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
		if ( ! in_array( $method, [ 'GET', 'HEAD' ], true ) ) return;
		ob_start( function( $html ) {
			if ( stripos( $html, '<html' ) === false || strlen( $html ) < 64 ) return $html;
			$html = preg_replace( '#<meta[^>]+http-equiv=[\'"]?Content-Security-Policy[\'"]?[^>]*>#i', '', $html );
			$html = preg_replace( '#<meta[^>]+name=[\'"]?generator[\'"]?[^>]*>#i', '', $html );
			$html = preg_replace_callback(
				'#(<script[^>]+type=[\'"]application/ld\+json[\'"][^>]*>)(.*?)(</script>)#is',
				function( $m ){
					$json = trim( $m[2] );
					$san  = $this->json_strip_emails( $json );
					return $m[1] . $san . $m[3];
				},
				$html
			);
			$html = preg_replace(
				'#<meta\s+(?:property|name)=["\'](?:og:email|profile:email|twitter:creator|twitter:site)["\'][^>]*>#i',
				'',
				$html
			);
			$html = preg_replace_callback(
				'#mailto:([a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,})#i',
				function( $m ){ return 'mailto:' . $this->encode_email( $m[1] ); },
				$html
			);
			$html = preg_replace_callback(
				'#(?<![\'"=])\b([a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,})\b#i',
				function( $m ){ return $this->encode_email( $m[1] ); },
				$html
			);
			$html = preg_replace( '#((?:href|src)=["\'][^"\']+)\?ver=[^"\']+(["\'])#i', '$1$2', $html );
			return $html;
		} );
	}
	private function json_strip_emails( string $json ) : string {
		$data = json_decode( $json, true );
		if ( ! is_array( $data ) ) return $json;
		$strip = function( &$node ) use ( &$strip ) {
			if ( is_array( $node ) ) {
				foreach ( $node as $k => &$v ) {
					if ( is_string( $k ) && strtolower( $k ) === 'email' ) {
						unset( $node[ $k ] );
						continue;
					}
					$strip( $v );
				}
			}
		};
		$strip( $data );
		$san = wp_json_encode( $data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
		return is_string( $san ) ? $san : $json;
	}
	public function send_security_headers() : void {
		if ( headers_sent() ) return;
		$this->add_header_once( 'X-Content-Type-Options', 'nosniff' );
		$this->add_header_once( 'X-Frame-Options',        'SAMEORIGIN' );
		$this->add_header_once( 'Referrer-Policy',        'no-referrer-when-downgrade' );
		$this->add_header_once( 'Permissions-Policy',     'geolocation=(), camera=(), microphone=(), payment=(), usb=(), xr-spatial-tracking=()' );
		$csp = [
			"default-src 'self'",
			"base-uri 'self'",
			"object-src 'none'",
			"frame-ancestors 'self'",
			"form-action 'self'",
			"img-src 'self' data: blob: https:",
			"font-src 'self' https: data:",
			"style-src 'self' 'unsafe-inline' https:",
			"script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com",
			"connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://stats.g.doubleclick.net",
			"frame-src 'self' https://www.googletagmanager.com",
			"upgrade-insecure-requests"
		];
		$this->add_header_once( 'Content-Security-Policy-Report-Only', implode( '; ', $csp ) );
	}
	public function remove_x_pingback_header( array $headers ) : array { unset( $headers['X-Pingback'] ); return $headers; }
	public function disable_emojis_tinymce( $plugins ) { if ( is_array( $plugins ) ) $plugins = array_diff( $plugins, [ 'wpemoji' ] ); return $plugins; }
	public function disable_embeds_rewrites( array $rules ) : array { foreach ( $rules as $rule => $rewrite ) { if ( false !== strpos( $rewrite, 'embed=true' ) ) unset( $rules[ $rule ] ); } return $rules; }
	public function disable_rss() : void { status_header( 410 ); wp_die( esc_html__( 'RSS feeds are disabled on this site.', 'monolit-shield' ), esc_html__( 'RSS disabled', 'monolit-shield' ), [ 'response' => 410 ] ); }
	public function disable_self_pingbacks( array &$links ) : void { $home = home_url(); foreach ( $links as $k => $url ) if ( 0 === strpos( $url, $home ) ) unset( $links[ $k ] ); }
	private function dequeue_google_fonts() : void {
		global $wp_styles;
		$known = [ 'google-fonts','fonts-googleapis','wp-block-library-theme','generate-fonts','astra-google-fonts','elementor-icons-shared-0-font' ];
		foreach ( $known as $h ) {
			if ( wp_style_is( $h, 'enqueued' ) )   wp_dequeue_style( $h );
			if ( wp_style_is( $h, 'registered' ) ) wp_deregister_style( $h );
		}
		if ( isset( $wp_styles->registered ) && is_array( $wp_styles->registered ) ) {
			foreach ( $wp_styles->registered as $handle => $obj ) {
				if ( ! empty( $obj->src ) ) {
					$src = $obj->src;
					if ( 0 === strpos( $src, '//' ) )      $src = ( is_ssl() ? 'https:' : 'http:' ) . $src;
					elseif ( 0 === strpos( $src, '/' ) )   $src = home_url( $src );
					$host = wp_parse_url( $src, PHP_URL_HOST );
					if ( $host && preg_match( '/(^|\.)(fonts\.googleapis\.com|fonts\.gstatic\.com)$/i', $host ) ) {
						wp_dequeue_style( $handle );
					}
				}
			}
		}
	}
	public function remove_jquery_migrate( WP_Scripts $scripts ) : void {
		if ( empty( $scripts->registered['jquery'] ) ) return;
		$d = $scripts->registered['jquery']->deps;
		if ( is_array( $d ) ) $scripts->registered['jquery']->deps = array_diff( $d, [ 'jquery-migrate' ] );
	}
	private function disable_comments_everywhere() : void {
		add_filter( 'comments_open', '__return_false', 20, 2 );
		add_filter( 'pings_open', '__return_false', 20, 2 );
		add_filter( 'feed_links_show_comments_feed', '__return_false', 10 );
		add_action( 'admin_menu', function () { remove_menu_page( 'edit-comments.php' ); }, 999 );
		add_action( 'wp_dashboard_setup', function () { remove_meta_box( 'dashboard_recent_comments', 'dashboard', 'normal' ); }, 20 );
		add_action( 'admin_bar_menu', function ( $bar ) { $bar->remove_node( 'comments' ); }, 99 );
		add_filter( 'comments_template', function () { return __DIR__ . '/views/blank-comments.php'; }, 1000 );
	}
	public function rest_harden( $result ) {
		if ( is_user_logged_in() ) return $result;
		if ( ! isset( $_SERVER['REQUEST_URI'] ) ) return $result;
		$path = wp_parse_url( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'], PHP_URL_PATH );
		if ( 0 === strpos( $path, '/wp-json/wp/v2/users' ) ) {
			return new WP_Error( 'rest_forbidden', __( 'REST endpoint not available.', 'monolit-shield' ), [ 'status' => 403 ] );
		}
		if ( 0 === strpos( $path, '/wp-json/oembed/1.0' ) ) {
			return new WP_Error( 'rest_forbidden', __( 'REST endpoint not available.', 'monolit-shield' ), [ 'status' => 403 ] );
		}
		return $result;
	}
	public function block_author_enum() : void {
		if ( is_admin() ) return;
		if ( isset( $_GET['author'] ) ) { wp_safe_redirect( home_url( '/' ), 301 ); exit; }
		if ( is_author() ) { status_header( 404 ); nocache_headers(); include get_query_template( '404' ) ?: ABSPATH . WPINC . '/theme-compat/404.php'; exit; }
	}
	public function mask_admin_url( $url, $path, $blog_id ) {
		return preg_replace( '#/wp-admin/#', '/' . MSHIELD_ADMIN_SLUG . '/', $url );
	}
	public function mask_site_admin_url( $url, $path, $scheme, $blog_id ) {
		if ( $scheme === 'admin' || ( is_string( $path ) && strpos( $path, 'wp-admin' ) === 0 ) ) {
			$url = preg_replace( '#/wp-admin/#', '/' . MSHIELD_ADMIN_SLUG . '/', $url );
		}
		return $url;
	}
	public function strip_asset_ver_front( $src, $handle ) { if ( is_admin() ) return $src; if ( strpos( $src, 'ver=' ) !== false ) $src = remove_query_arg( 'ver', $src ); return $src; }
	public function cloak_emails( $html ) { if ( is_admin() || ! is_string( $html ) || $html === '' ) return $html; $html = preg_replace_callback( '#mailto:([a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,})#i', function( $m ){ return 'mailto:' . $this->encode_email( $m[1] ); }, $html ); $html = preg_replace_callback( '#(?<![\'"=])\b([a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,})\b#i', function( $m ){ return $this->encode_email( $m[1] ); }, $html ); return $html; }
	private function encode_email( $email ) { $out=''; foreach ( str_split( $email ) as $c ) $out .= '&#' . ord( $c ) . ';'; return $out; }
	private function add_header_once( $name, $value ) : void { if ( function_exists( 'headers_list' ) ) { foreach ( headers_list() as $h ) if ( 0 === stripos( $h, $name . ':' ) ) return; } header( $name . ': ' . $value ); }
	private function is_login_or_admin() : bool { $script = basename( $_SERVER['PHP_SELF'] ?? '' ); return is_admin() || ( 'wp-login.php' === $script ); }
	public function sanitize_filename_latin( string $filename ) : string { $ext = pathinfo( $filename, PATHINFO_EXTENSION ); $basename = pathinfo( $filename, PATHINFO_FILENAME ); $normalized = remove_accents( $basename ); $normalized = strtolower( $normalized ); $normalized = preg_replace( '/[^a-z0-9\.\-_]+/i', '-', $normalized ); $normalized = preg_replace( '/-{2,}/', '-', $normalized ); $normalized = trim( $normalized, '-._' ); return $ext ? $normalized . '.' . strtolower( $ext ) : $normalized; }
	private function ensure_blank_comments_view() : void { if ( ! file_exists( __DIR__ . '/views/blank-comments.php' ) ) { @mkdir( __DIR__ . '/views', 0755, true ); @file_put_contents( __DIR__ . '/views/blank-comments.php', "<?php\nif ( ! defined( 'ABSPATH' ) ) { exit; }\n// Comments intentionally disabled.\n" ); } }
}
Monolit_Shield::boot();
endif;
